- name: stat node
  stat:
    path: /opt/{{ node_file }}/bin/
  register: node_stat

- name: download nodejs
  when: not node_stat.stat.exists
  get_url:
    url: "{{ node_download_url }}"
    dest: /tmp/nodejs.tar.xz

- name: unarchive node js
  become: true
  when: not node_stat.stat.exists
  unarchive:
    src: /tmp/nodejs.tar.xz
    dest: /opt/
    remote_src: true

- name: append extra config to zshrc
  when: not node_stat.stat.exists
  blockinfile:
    state: present 
    marker: '#load nodejs path'
    block: |
      PATH=${PATH}:/opt/{{ node_file }}/bin/
    dest: ~/.zshrc

- name: create node bin link
  file:
    src: /opt/{{ node_file }}/bin/node
    dest: /usr/bin/node
    state: link

- name: create npm bin link
  file:
    src: /opt/{{ node_file }}/bin/npm
    dest: /usr/bin/npm
    state: link
